version: 0.0
os: linux
files:
  - source: html
    destination: /var/www/html/
  - source: scripts
    destination: /home/ec2-user/scripts/
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root

