version: 0.0
os: linux
files:
  - source: html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root

